### ISSUE TITLE
Mod folder not created

### ISSUE THREAD

**Issue by ZupZ3r0** [RealityMachina/PhoenixPointModInjector#2]
Hi, I ran the injector.exe and got some successful output on the console.
Then I started the game, but no mod folder was created.
It should be located in the main installation folder i guess?

Then I just created my own mod folder and placed some mods into it. Nothing happend in game.

Any ideas? Maybe the latest patch has broken it?

**Comment by gunnergoz** [comment]
This happened to me too, but the console ran so fast I could not read it before it disappeared. No mods folder was created. Perhaps has to do with using non-standard file folder locations?

**Comment by ZupZ3r0** [comment]
@gunnergoz have you placed the mod-loader files into ...\PhoenixPointWin64_Data\Managed?
I had it in the wrong directory (only the main) and the console also disappeared directly and didn' work.
After placing it in the correct subdirectory the console should stay open with some output.

But even then nothing happened for me :-(

**Comment by gunnergoz** [comment]
Yes, I followed the instructions but I'll try it again, perhaps I got the folder wrong.

**Comment by gunnergoz** [comment]
OK, that must have been the problem, the mods folder is now there. Thanks!

**Comment by Pointer773** [comment]
Having the same problem, I fear.  I've got it in the correct folder, and the console indicated that it finished correctly, but it won't create the mods folder on game startup.  I've tried reverting the file and re-running a freshly downloaded copy of the injector, and still no dice.  Manually creating the folder doesn't help.  Mods placed there are not being utilized.

**Comment by Pointer773** [comment]
I figured it out!  For some reason, instead of the game folder, the Mods folder was created directly in the drive directory (for me, E:\Mods).  This is apparently where my game is looking for them, as mods placed in that folder are working ^^"

**Comment by ZupZ3r0** [comment]
Thanks @Pointer773 ! You are right, I also have a Mod folder in the drive directory and placing mods inside there works fine. Funny thing: its also E:\Mods :-D

So maybe there is something wrong with detecting the correct game directory. But at least there is a simple workaround.

**Comment by crerigan** [comment]
How can i mount it on GamePass Version? Folder structure is completely different PLUS are in the classic not owned folder like a windowsapp or something like that

**Comment by RealityMachina** [comment]
For the wrong folder thing: is the game installed in a directory where it's inside the Program Files or Program Files (x86) directory of the drive? Windows protects those folders so it might be why I'm unable to replicate this issue on my system.

@crerigan 

Game Pass games are installed like a normal Windows Store app, so Windows encrypts their installation directories. Unfortunately until Microsoft starts allowing unencrypted installs, I don't think it'll be possible to mod Microsoft Store installed games.

**Comment by ZupZ3r0** [comment]
@RealityMachina 
No, its installed on a seperate Disc, the Path is **E:\PhoenixPoint**, the created mod folder after running the patcher is at **E:\Mods**.

**Comment by Ijwu** [comment]
@mbiel86 The directory your modloader files should be in would be `E:\PhoenixPoint\PhoenixPointWin64_Data\Managed`. This would end up with a mod folder at `E:\PhoenixPoint\Mods`. Could you confirm the PPML files are in that first directory?

I don't think it's impossible to get this to work for the Game Pass version, it's just a real headache and probably only for people who are sure they know what they're doing.

**Comment by ZupZ3r0** [comment]
Thanks for all responses. With a fresh reinstall of the game and the executable placed in the correct folder before running it, it's working as intended.
So I guess if you run it from a wrong place at first, then the wrong path to the mod-folder is registered somewhere. Even if you move the executable and run it again it does not change this initially wrong path.

Easy solution: just do it right in the first place ;-)
Complete solution: dig in the code and have a look what happens with that path...but maybe not worth the effort
